# CrewAI Configuration for Wing Commander Saga to Godot Migration
# Using DeepSeek V3.1 as the primary cognitive model

# Global LLM configuration
llm:
  model: deepseek-ai/DeepSeek-V3.1
  temperature: 0.7
  max_tokens: 4096
  base_url_env_var: "DEEPSEEK_BASE_URL"  # Load base URL from environment variable
  api_key_env_var: "DEEPSEEK_API_KEY"   # Load API key from environment variable

# Default agent configuration
default_agent:
  verbose: true
  allow_delegation: true
  max_rpm: 60  # Rate limiting to avoid API overuse
  cache: true

# Process configuration
process:
  # Sequential for atomic tasks
  sequential:
    timeout: 300  # 5 minutes timeout
  # Hierarchical for complex workflows
  hierarchical:
    manager_llm: deepseek-ai/DeepSeek-V3.1
    timeout: 600  # 10 minutes timeout

# Memory configuration
memory:
  enabled: true
  embedder:
    provider: huggingface
    config:
      model: sentence-transformers/all-MiniLM-L6-v2

# Logging configuration
logging:
  level: INFO
  file: ./logs/crewai.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"