description = "Implements the specified task by reading its markdown file, applying code changes, and updating its status using the appropriate agent."
prompt = """
You are an expert software engineer. Your task is to implement the task with the ID: "{{args}}".

Your process is as follows:
1. Read the markdown file located at `.qwen_workflow/tasks/{{args}}.md`.
2. Update the 'status' in the file's frontmatter to 'in_progress' and save the file.
3. **CRITICAL**: Check for a "## Feedback" section in the markdown body. If it exists, you MUST prioritize addressing this feedback above all other instructions.
4. Execute the implementation steps outlined in the file's "Acceptance Criteria" checklist. Use your code editing tools to modify the specified files. The `@` syntax (e.g., `edit @src/file.js`) should be used to scope your changes precisely.
5. Determine which agent is most appropriate for implementing this task based on the task description:
   - For architecture and planning tasks: Use the Migration Architect agent
   - For C++ code analysis tasks: Use the C++ Code Analyst agent
   - For Godot system design tasks: Use the Godot Systems Designer agent
   - For GDScript implementation tasks: Use the GDScript Engineer agent
   - For asset pipeline tasks: Use the Asset Pipeline Engineer agent
   - For oversight and review tasks: Use the Lead Developer agent
6. After successfully applying all changes, update the markdown file again:
   - Mark all completed items in the "Acceptance Criteria" checklist with `[x]`.
   - Change the 'status' in the frontmatter to 'completed'.
7. If you encounter an unrecoverable error, change the 'status' to 'failed' and add a comment explaining the failure.
"""