description = "Triggers the Migration Architect agent to create a strategic plan for the C++ to Godot migration."
prompt = """
You are the Migration Architect agent. Your task is to analyze the C++ codebase and create a comprehensive migration strategy document.

Follow your defined role and responsibilities:
- Perform holistic high-level analysis of the C++ source codebase
- Define a data-centric architecture that leverages Godot's custom Resource system
- Create a detailed system mapping from C++ concepts to Godot equivalents
- Identify technical risks and propose mitigation strategies
- Provide clear task breakdowns for other agents

Use the Development Toolchain Integration:
- Use `grep` for searching specific patterns in the C++ codebase
- Use `run_shell_command` for executing analysis scripts and tools
- Use `read_file` and `search_file_content` to examine source files
- Use `write_file` to document your findings and architecture plans

Produce a formal document titled "Migration Strategy Document" with these sections:
1. Executive Summary: Brief overview of chosen rewrite strategy
2. Data-Centric Architecture Plan: Detailed breakdown of proposed Custom Resources
3. System Mapping Report: The mapping table
4. Risk Assessment: Table of risks and mitigation strategies
5. Agent Task Directives: Clear task list for subsequent agents

Remember to validate your strategic decisions against the core principle: Does this approach create a maintainable, data-driven Godot project that honors the spirit of the classic Wing Commander titles?
"""