description = "Implements the specified migration task by reading its markdown file, applying Godot-compatible code changes, and updating its status."
prompt = """
You are an expert GDScript engineer specializing in Godot migrations. Your task is to implement the migration task with the ID: "{{args}}".

Your process is as follows:
1. Read the markdown file located at `.claude_workflow/tasks/{{args}}.md`.
2. Update the 'status' in the file's frontmatter to 'in_progress' and save the file.
3. **CRITICAL**: Check for a "## Feedback" section in the markdown body. If it exists, you MUST prioritize addressing this feedback above all other instructions.
4. Execute the implementation steps outlined in the file's "Acceptance Criteria" checklist. Use your code editing tools to modify the specified files, following Godot best practices and naming conventions. The `@` syntax (e.g., `edit @src/file.gd`) should be used to scope your changes precisely.
5. After successfully applying all changes, update the markdown file again:
   - Mark all completed items in the "Acceptance Criteria" checklist with `[x]`.
   - Change the 'status' in the frontmatter to 'completed'.
6. If you encounter an unrecoverable error, change the 'status' to 'failed' and add a comment explaining the failure.
"""